### PR TITLE
fix(ui): start using SES

### LINKED ISSUE #875: SES 0.14.2 incompatibility with Parcel 1
@samsiegart isolated an incompatible interaction between Parcel bundler and SES 0.14.2, where the bundler injects `Object.defineProperty(module.exports, '__esModule', {value: true})`, specifically into the preamble of `commons.js`.

While we encourage developers to inject SES as a script ahead of any modules to avoid passing it through a source-to-source translator that corrupts its intent, we do currently attempt to support bundlers. We have a Parcel integration test that oddly does not reveal this flaw.

The problem is that we capture `Object` off of `globalThis` and reexport the name `Object`, so `Object.defineProperty` in the preamble occurs within a temporal dead-zone for the module scoped constant.

We can mitigate this problem by exporting Object by a different name, like OBJECT, OriginalObject, OG (Objet Genè), Objekt, or Abject.

### PR DESCRIPTION
**Pull request by michaelfig**
Closes endojs/endo#875

These are fixes I needed to use SES on the UI side.

By preparing this, it should now be possible to start migrating to eventual-send instead of a JSON-RPC-like connection.

### CODE REVIEW

File: ui/public/src/install-ses-lockdown.js [hunk 1]
```diff
@@ -0,0 +1,14 @@
+/* eslint-disable import/no-extraneous-dependencies */
+import 'ses/dist/ses.umd'; // adds lockdown, harden, and Compartment
+import '@agoric/eventual-send/shim'; // adds support needed by E
+
+// Help lock down the JS environment.  The start compartment (current evaluation context)
+// can still access powerful globals, but this start compartment can use `new Compartment(...)`
+// to evaluate code with stricter confinement.
+lockdown({
+  __allowUnsafeMonkeyPatching__: true,
```
Comment (erights) [inline ui/public/src/install-ses-lockdown.js]: Why?

Comment (michaelfig) [reply ui/public/src/install-ses-lockdown.js]: It was cargo-culted from a React app.  I will see if I can do without.

Comment (michaelfig) [reply ui/public/src/install-ses-lockdown.js]: Yep, looks like it works fine without.  Removing it.

File: yarn.lock [hunk 2]
```diff
@@ -7610,7 +7610,7 @@ ses@^0.12.6:
     "@agoric/make-hardener" "^0.1.2"
     "@agoric/transform-module" "^0.4.1"
 
-ses@^0.14.1:
+ses@^0.14.1, ses@^0.14.2:
```
Comment (kriskowal) [inline yarn.lock:7613]: What is entraining the prior version? Can you `yarn why ses`?

File: ui/public/src/install-ses-lockdown.js [hunk 3]
```diff
@@ -0,0 +1,13 @@
+/* eslint-disable import/no-extraneous-dependencies */
+import 'ses/dist/ses.umd'; // adds lockdown, harden, and Compartment
```
Comment (kriskowal) [inline ui/public/src/install-ses-lockdown.js:2]: Okay. And this can be `import 'ses'` when I release a version with `"module": "./dist/ses.umd.js"` in `package.json`?

**Review by kriskowal — APPROVED** [review]

File: ui/public/src/install-ses-lockdown.js (hunk 3 above)
Comment (michaelfig) [reply ui/public/src/install-ses-lockdown.js:2]: Yes, I think so.

File: yarn.lock (hunk 2 above)
Comment (michaelfig) [reply yarn.lock:7613]: The prior version comes from other published `@agoric/...` dependencies in the `yarn.lock`.  Each dapp currently is expected to be able to function even if you don't use `agoric install`, but use `yarn install` to get all its dependencies.  So, the `yarn.lock` typically drifts a little bit behind what the current `agoric-sdk` has, until the SDK has been published and the dapp's `yarn.lock` can be updated.
